name: Rust

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: git-checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: cargo build --release
