name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: git-checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: cargo build --release
      
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        
      - name: Release
        run: git checkout -b release/v${{ github.event.inputs.versionName }}
